export const USER_GET_PROGRESS = "USER_GET_PROGRESS";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_ERROR = "USER_GET_ERROR";

export const USER_POST_PROGRESS = "USER_POST_PROGRESS";
export const USER_POST_SUCCESS = "USER_POST_SUCCESS";
export const USER_POST_ERROR = "USER_POST_ERROR";

export const USER_DELETE_PROGRESS = "USER_DELETE_PROGRESS";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_ERROR = "USER_DELETE_ERROR";
